=pod

=encoding utf8

=head1 NAME

require::relative - like require for relative paths

=head1 SYNOPSIS

	use require::relative RELATIVE_FILE;

	use require::relative "../test-helper.pl";

=head1 DESCRIPTION

Behaves like require but accepts relative file name.

Primary motivation is for usage in tests where multiple tests can
share configuration or setup.

=head1 AUTHOR

Branislav Zahradník <barney@cpan.org>

=head1 COPYRIGHT AND LICENSE

This module is distributed under Artistic license 2.0

=cut
